channels:
    - conda-forge
    - defaults
name:
    stardist-cpu
dependencies:
    - imageio
    - jupyter
    - h5py
    - napari
    - pip
    - python 3.7
    - scikit-image
    - tensorflow 1.14
    - tqdm
    - pip:
        - stardist
